# Generated by Django 4.0.4 on 2022-08-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greg_middle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Greg (middle)(e.g., 197b for the second edition of Hamlet)')),
                ('book_edition', models.CharField(blank=True, max_length=200, null=True, verbose_name='Book Edition')),
                ('play_edition', models.CharField(blank=True, max_length=200, null=True, verbose_name='Play Edition')),
                ('blackletter', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='DEEP #')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('greg_full', models.CharField(blank=True, max_length=200, null=True, verbose_name='Greg Ful')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='PlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep_id', models.CharField(blank=True, max_length=20, null=True)),
                ('authors_display', models.CharField(blank=True, max_length=200, null=True, verbose_name='Authors Display')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_alternative_keywords', models.CharField(default='', max_length=200, null=True, verbose_name='Title Alternative Keywords')),
                ('greg', models.CharField(max_length=200, verbose_name='Greg (Brief)(e.g., 197 for Hamlet)')),
                ('genre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Genre (Annals)')),
                ('date_first_publication', models.CharField(max_length=200, verbose_name='Date of First Publication')),
                ('date_first_publication_display', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of First Publication Display')),
                ('date_first_performance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of First Performance')),
                ('company_first_performance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company First Performance')),
                ('total_editions', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total Editions')),
                ('stationers_register', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationers Register')),
                ('british_drama', models.IntegerField(blank=True, null=True, verbose_name='British Drama')),
                ('genre_wiggins', models.CharField(blank=True, max_length=200, null=True, verbose_name='Genre (Wiggins)')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(blank=True, choices=[('Single-Play Playbook', 'Single-Play Playbook'), ('Collection', 'Collection'), ('Play in Collection', 'Play in Collection')], max_length=200, null=True, verbose_name='Record Type')),
                ('collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection')),
                ('year', models.CharField(blank=True, max_length=200, null=True, verbose_name='Year (of publication)')),
                ('year_int', models.IntegerField(blank=True, null=True, verbose_name='Year INT')),
                ('deep_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='DEEP #')),
                ('deep_id_display', models.CharField(blank=True, max_length=200, null=True, verbose_name='DEEP Display #')),
                ('greg_full', models.CharField(blank=True, max_length=200, null=True, verbose_name='Greg #(i.e., Greg full, e.g., 197b(*) and 197b(†) for the two issues of the second edition of Hamlet)')),
                ('stc', models.CharField(blank=True, max_length=200, null=True, verbose_name='STC/Wing #')),
                ('format', models.CharField(blank=True, max_length=200, null=True, verbose_name='Format')),
                ('leaves', models.CharField(blank=True, max_length=200, null=True, verbose_name='Leaves')),
                ('company_attribution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Attribution')),
                ('composition_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Composition Date')),
                ('date_first_publication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of First Publication')),
                ('title_page_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Title')),
                ('title_page_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Author')),
                ('title_page_performance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Performance')),
                ('title_page_latin_motto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Latin Motto')),
                ('title_page_imprint', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Imprint')),
                ('title_page_illustration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Illustration')),
                ('title_page_modern_spelling', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title Page: Modern Spelling')),
                ('paratext_explicit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Explicit')),
                ('paratext_errata', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Errata')),
                ('paratext_commendatory_verses', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Commendatory Verses')),
                ('paratext_to_the_reader', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: To the Reader')),
                ('paratext_dedication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Dedication')),
                ('paratext_argument', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Argument')),
                ('paratext_actor_list', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Actor List')),
                ('paratext_charachter_list', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Character List')),
                ('paratext_other_paratexts', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paratext: Other Paratexts')),
                ('stationer_colophon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Colophon')),
                ('stationer_printer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Printer')),
                ('stationer_publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Publisher')),
                ('stationer_bookseller', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Bookseller')),
                ('stationer_entries_in_register', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Entries in Register')),
                ('stationer_additional_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stationer: Additional Notes')),
                ('theater_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Theater Type')),
                ('theater', models.CharField(blank=True, max_length=200, null=True, verbose_name='Theater')),
                ('variants', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variants')),
                ('independent_playbook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Independent Playbook')),
                ('also_in_collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='Also In Collection')),
                ('collection_full', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Full')),
                ('collection_middle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Middle')),
                ('collection_brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collection Brief')),
                ('variant_edition_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant Edition ID')),
                ('variant_newish_primary_deep_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant Newish')),
                ('author_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author Status')),
                ('srstationer', models.CharField(blank=True, max_length=200, null=True, verbose_name='SrStationer')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher')),
                ('printer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Printer')),
                ('also_in_collection_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='also_in_collection_link_fk', to='main.link')),
                ('collection_contains', models.ManyToManyField(blank=True, related_name='collection_contains', to='main.link')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_company', to='main.company')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_edition', to='main.edition')),
                ('in_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_collection_link_fk', to='main.link')),
                ('independent_playbook_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='independent_playbook_link_fk', to='main.link')),
                ('variant_links', models.ManyToManyField(blank=True, to='main.link')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='authors',
            field=models.ManyToManyField(to='main.person'),
        ),
        migrations.AddField(
            model_name='edition',
            name='play_type',
            field=models.ManyToManyField(to='main.playtype'),
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.title'),
        ),
    ]
