import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_id', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Edition ID')),
                ('authors_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Authors Display')),
                ('greg_middle', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Greg (middle)(e.g., 197b for the second edition of Hamlet)')),
                ('book_edition', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Book Edition')),
                ('play_edition', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Edition')),
                ('play_type_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Type: Filter')),
                ('play_type_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Type: Display')),
                ('blackletter', models.CharField(blank=True, max_length=255, null=True)),
                ('collection', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection')),
                ('variants', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Variants')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(blank=True, choices=[('Single-Play Playbook', 'Single-Play Playbook'), ('Collection', 'Collection'), ('Play in Collection', 'Play in Collection')], max_length=5000, null=True, verbose_name='Record Type')),
                ('collection', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection')),
                ('item_title', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Item Specific Title')),
                ('item_alternative_keywords', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Item Specific Alternative Keywords')),
                ('year', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Year (of publication)')),
                ('year_int', models.IntegerField(blank=True, null=True, verbose_name='Year INT')),
                ('deep_id', models.CharField(blank=True, max_length=5000, null=True, verbose_name='DEEP #')),
                ('deep_id_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='DEEP Display #')),
                ('greg_full', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Greg #(i.e., Greg full, e.g., 197b(*) and 197b(†) for the two issues of the second edition of Hamlet)')),
                ('stc', models.CharField(blank=True, max_length=5000, null=True, verbose_name='STC/Wing #')),
                ('format', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Format')),
                ('leaves', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Leaves')),
                ('title_page_company_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company (Title Page Attribution) Display')),
                ('date_first_publication', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Publication')),
                ('title_page_title', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Title')),
                ('title_page_author', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Author')),
                ('title_page_author_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Author Filter')),
                ('title_page_performance', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Performance')),
                ('title_page_latin_motto', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Latin Motto')),
                ('title_page_imprint', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Imprint')),
                ('title_page_has_latin', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Has Latin')),
                ('title_page_genre', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Genre: Playbook Attribution')),
                ('title_page_illustration', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Illustration')),
                ('title_page_modern_spelling', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Modern Spelling')),
                ('paratext_author', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Author')),
                ('paratext_explicit', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Explicit')),
                ('paratext_errata', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Errata')),
                ('paratext_commendatory_verses', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Commendatory Verses')),
                ('paratext_to_the_reader', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: To the Reader')),
                ('paratext_dedication', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Dedication')),
                ('paratext_argument', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Argument')),
                ('paratext_actor_list', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Actor List')),
                ('paratext_charachter_list', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Character List')),
                ('paratext_other_paratexts', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Other Paratexts')),
                ('stationer_colophon', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Colophon')),
                ('stationer_printer_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Printer Display')),
                ('stationer_publisher_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Publisher Display')),
                ('stationer_license', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: License')),
                ('stationer_imprint_location', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Imprint Location')),
                ('stationer_bookseller_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Bookseller Display')),
                ('stationer_additional_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Additional Notes')),
                ('theater_type', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Theater Type')),
                ('theater', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Theater')),
                ('independent_playbook', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Independent Playbook')),
                ('also_in_collection', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Also In Collection')),
                ('collection_full', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Full')),
                ('collection_middle', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Middle')),
                ('collection_brief', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Brief')),
                ('variant_edition_id', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variant Edition ID')),
                ('variant_newish_primary_deep_id', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variant Newish')),
                ('author_status', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Author Status')),
                ('srstationer', models.CharField(blank=True, max_length=5000, null=True, verbose_name='SrStationer')),
                ('publisher', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Publisher')),
                ('printer', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Printer')),
                ('also_in_collection_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='also_in_collection_link_fk', to='main.item')),
                ('collection_contains', models.ManyToManyField(blank=True, related_name='collection_contains_fk', to='main.item')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_edition', to='main.edition')),
                ('in_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_collection_link_fk', to='main.item')),
                ('independent_playbook_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='independent_playbook_link_fk', to='main.item')),
                ('title_page_company_filter', models.ManyToManyField(blank=True, to='main.company')),
                ('variant_links', models.ManyToManyField(blank=True, to='main.item')),
                ('stationer_bookseller', models.ManyToManyField(blank=True, related_name='stationer_bookseller', to='main.person')),
                ('stationer_printer', models.ManyToManyField(blank=True, related_name='stationer_printer', to='main.person')),
                ('stationer_publisher', models.ManyToManyField(blank=True, related_name='stationer_publisher', to='main.person')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='authors',
            field=models.ManyToManyField(blank=True, to='main.person'),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.FloatField(blank=True, null=True, verbose_name='Work ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Title')),
                ('title_alternative_keywords', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Work Alternative Keywords')),
                ('greg', models.CharField(blank=True, max_length=5000, verbose_name='Greg (Brief)(e.g., 197 for Hamlet)')),
                ('brit_drama_number', models.CharField(blank=True, max_length=5000, null=True, verbose_name='BritDrama #')),
                ('genre_annals_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Display Genre (Annals)')),
                ('genre_annals_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Filter Genre (Annals)')),
                ('genre_brit_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Display Genre (BritDrama)')),
                ('genre_brit_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Filter Genre (BritDrama)')),
                ('date_first_publication', models.CharField(blank=True, max_length=5000, verbose_name='Date of First Publication')),
                ('date_first_publication_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Publication Display')),
                ('date_first_performance', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (Annals): Display')),
                ('date_first_performance_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (Annals): Filter')),
                ('date_first_performance_brit_filter', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (BritDrama)')),
                ('date_first_performance_brit_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (BritDrama) (display)')),
                ('company_first_performance_annals_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company First Performance (Annals)(display)')),
                ('company_first_performance_brit_display', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company of First Performance (BritDrama) (display)')),
                ('total_editions', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Total Editions')),
                ('stationers_register', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationers Register')),
                ('genre_wiggins', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Genre (Wiggins)')),
                ('stationer_entries_in_register', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Entries in Register')),
                ('company_first_performance_annals_filter', models.ManyToManyField(blank=True, related_name='company_first_performance_annals_filter', to='main.company')),
                ('company_first_performance_brit_filter', models.ManyToManyField(blank=True, to='main.company')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.title'),
        ),
    ]
