# Generated by Django 4.0.4 on 2022-12-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='british_drama',
        ),
        migrations.AddField(
            model_name='title',
            name='brit_drama_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='BritDrama #'),
        ),
        migrations.AddField(
            model_name='title',
            name='company_first_performance_brit_display',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company of First Performance (BritDrama) (display)'),
        ),
        migrations.AddField(
            model_name='title',
            name='company_first_performance_brit_filter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company of First Performance (BritDrama): filter terms'),
        ),
        migrations.AddField(
            model_name='title',
            name='date_first_performance_brit_display',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of First Performance (BritDrama) (display)'),
        ),
        migrations.AddField(
            model_name='title',
            name='date_first_performance_brit_filter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of First Performance (BritDrama)'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre_brit_display',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Display Genre (BritDrama)'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre_brit_filter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Genre (BritDrama): filter terms'),
        ),
    ]
