# Generated by Django 4.0.4 on 2022-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_name_alter_edition_book_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genre_annals_display',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Display Genre (Annals)'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre_annals_filter',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Filter Genre (Annals)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_brit_filter',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Filter Genre (BritDrama)'),
        ),
    ]
