# Generated by Django 4.0.4 on 2023-01-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_title_genre_title_genre_annals_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_page_author_filter',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title Page: Author Filter'),
        ),
    ]
