# Generated by Django 4.0.4 on 2023-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_title_company_first_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='company_first_performance_annals_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company First Performance (Annals):filter'),
        ),
        migrations.AlterField(
            model_name='title',
            name='company_first_performance_annals_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company First Performance (Annals)(display)'),
        ),
    ]
