# Generated by Django 4.0.4 on 2023-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_title_company_first_performance_annals_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='play_type',
        ),
        migrations.AddField(
            model_name='edition',
            name='play_type_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Play Type: Display'),
        ),
        migrations.AddField(
            model_name='edition',
            name='play_type_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Play Type: Filter'),
        ),
        migrations.DeleteModel(
            name='PlayType',
        ),
    ]
