# Generated by Django 4.0.4 on 2023-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_edition_play_type_edition_play_type_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stationer_imprint_location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Imprint Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_license',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: License'),
        ),
    ]
