# Generated by Django 4.0.4 on 2023-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_stationer_imprint_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_page_genre',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Genre: Playbook Attribution'),
        ),
    ]
