# Generated by Django 4.0.4 on 2023-01-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_title_page_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_page_has_latin',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title Page: Has Latin'),
        ),
    ]
