# Generated by Django 4.0.4 on 2023-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_title_page_has_latin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stationer_bookseller_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Bookseller Filter'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_printer_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Printer Filter'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_publisher_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Publisher Filter'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_bookseller',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Bookseller Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_printer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Printer Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_publisher',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Publisher Display'),
        ),
    ]
