# Generated by Django 4.0.4 on 2023-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_item_stationer_bookseller_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='deep_id',
        ),
        migrations.AddField(
            model_name='item',
            name='paratext_author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Paratext: Author'),
        ),
    ]
