# Generated by Django 4.0.4 on 2023-01-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_title_deep_id_item_paratext_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='temp',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Djanog is terrible'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='stationer_bookseller',
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_bookseller',
            field=models.ManyToManyField(related_name='stationer_bookseller', to='main.person'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='stationer_printer',
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_printer',
            field=models.ManyToManyField(related_name='stationer_printer', to='main.person'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='stationer_publisher',
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_publisher',
            field=models.ManyToManyField(related_name='stationer_publisher', to='main.person'),
        ),
    ]
