# Generated by Django 4.0.4 on 2023-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_item_temp_remove_item_stationer_bookseller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stationer_bookseller_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stationer_printer_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stationer_publisher_filter',
        ),
        migrations.RemoveField(
            model_name='title',
            name='authors_display',
        ),
        migrations.AddField(
            model_name='edition',
            name='authors_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Authors Display'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_bookseller_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Bookseller Display'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_printer_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Printer Display'),
        ),
        migrations.AddField(
            model_name='item',
            name='stationer_publisher_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Stationer: Publisher Display'),
        ),
    ]
