# Generated by Django 4.0.4 on 2023-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_item_stationer_bookseller_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='temp',
        ),
        migrations.AddField(
            model_name='edition',
            name='collection',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='title',
            name='work_id',
            field=models.FloatField(blank=True, null=True, verbose_name='Work ID'),
        ),
    ]
