# Generated by Django 4.0.4 on 2023-02-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_item_temp_edition_collection_title_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edition_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Edition ID'),
        ),
    ]
