# Generated by Django 4.0.4 on 2023-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_edition_edition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company_attribution',
        ),
        migrations.AddField(
            model_name='item',
            name='title_page_company_display',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company (Title Page Attribution) Display'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_page_company_filter',
            field=models.ManyToManyField(blank=True, to='main.company'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='authors',
            field=models.ManyToManyField(blank=True, to='main.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_bookseller',
            field=models.ManyToManyField(blank=True, related_name='stationer_bookseller', to='main.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_printer',
            field=models.ManyToManyField(blank=True, related_name='stationer_printer', to='main.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_publisher',
            field=models.ManyToManyField(blank=True, related_name='stationer_publisher', to='main.person'),
        ),
        migrations.RemoveField(
            model_name='title',
            name='company_first_performance_annals_filter',
        ),
        migrations.AddField(
            model_name='title',
            name='company_first_performance_annals_filter',
            field=models.ManyToManyField(blank=True, related_name='company_first_performance_annals_filter', to='main.company'),
        ),
        migrations.RemoveField(
            model_name='title',
            name='company_first_performance_brit_filter',
        ),
        migrations.AddField(
            model_name='title',
            name='company_first_performance_brit_filter',
            field=models.ManyToManyField(blank=True, to='main.company'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_publication',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Date of First Publication'),
        ),
        migrations.AlterField(
            model_name='title',
            name='greg',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Greg (Brief)(e.g., 197 for Hamlet)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_alternative_keywords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Work Alternative Keywords'),
        ),
    ]
