# Generated by Django 4.0.4 on 2023-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_item_company_remove_item_company_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date_first_performance_filter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Date of First Performance (Annals): Filter'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_performance',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Date of First Performance (Annals): Display'),
        ),
    ]
