# Generated by Django 4.0.4 on 2023-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_title_date_first_performance_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edition_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Edition Specific Title'),
        ),
    ]
