# Generated by Django 4.0.4 on 2023-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_edition_edition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edition_alternative_keywords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Edition Specific Alternative Keywords'),
        ),
    ]
