# Generated by Django 4.0.4 on 2023-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_edition_edition_alternative_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='edition_alternative_keywords',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='edition_title',
        ),
        migrations.AddField(
            model_name='item',
            name='item_alternative_keywords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Item Specific Alternative Keywords'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item Specific Title'),
        ),
    ]
