# Generated by Django 4.0.4 on 2023-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_edition_edition_alternative_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='authors_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Authors Display'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='book_edition',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Book Edition'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='collection',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='edition_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Edition ID'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='greg_middle',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Greg (middle)(e.g., 197b for the second edition of Hamlet)'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='play_edition',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Edition'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='play_type_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Type: Display'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='play_type_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Play Type: Filter'),
        ),
        migrations.AlterField(
            model_name='item',
            name='also_in_collection',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Also In Collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='author_status',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Author Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection_brief',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Brief'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection_full',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Full'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection_middle',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Collection Middle'),
        ),
        migrations.AlterField(
            model_name='item',
            name='composition_date',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Composition Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_first_publication',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Publication'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deep_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='DEEP #'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deep_id_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='DEEP Display #'),
        ),
        migrations.AlterField(
            model_name='item',
            name='format',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='item',
            name='greg_full',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Greg #(i.e., Greg full, e.g., 197b(*) and 197b(†) for the two issues of the second edition of Hamlet)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='independent_playbook',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Independent Playbook'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_alternative_keywords',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Item Specific Alternative Keywords'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Item Specific Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='leaves',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Leaves'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_actor_list',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Actor List'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_argument',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Argument'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_author',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Author'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_charachter_list',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Character List'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_commendatory_verses',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Commendatory Verses'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_dedication',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Dedication'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_errata',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Errata'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_explicit',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Explicit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_other_paratexts',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: Other Paratexts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='paratext_to_the_reader',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Paratext: To the Reader'),
        ),
        migrations.AlterField(
            model_name='item',
            name='printer',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Printer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='item',
            name='record_type',
            field=models.CharField(blank=True, choices=[('Single-Play Playbook', 'Single-Play Playbook'), ('Collection', 'Collection'), ('Play in Collection', 'Play in Collection')], max_length=5000, null=True, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='srstationer',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='SrStationer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_additional_notes',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_bookseller_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Bookseller Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_colophon',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Colophon'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_entries_in_register',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Entries in Register'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_imprint_location',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Imprint Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_license',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: License'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_printer_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Printer Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_publisher_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Publisher Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stc',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='STC/Wing #'),
        ),
        migrations.AlterField(
            model_name='item',
            name='theater',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Theater'),
        ),
        migrations.AlterField(
            model_name='item',
            name='theater_type',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Theater Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_author',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Author'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_author_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Author Filter'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_company_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company (Title Page Attribution) Display'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_genre',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Genre: Playbook Attribution'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_has_latin',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Has Latin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_illustration',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Illustration'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_imprint',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Imprint'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_latin_motto',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Latin Motto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_modern_spelling',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Modern Spelling'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_performance',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Performance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_page_title',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title Page: Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variant_edition_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variant Edition ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variant_newish_primary_deep_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variant Newish'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variants',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variants'),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Year (of publication)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='deep_id',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='DEEP #'),
        ),
        migrations.AlterField(
            model_name='link',
            name='greg_full',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Greg Ful'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='title',
            name='brit_drama_number',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='BritDrama #'),
        ),
        migrations.AlterField(
            model_name='title',
            name='company_first_performance_annals_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company First Performance (Annals)(display)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='company_first_performance_brit_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Company of First Performance (BritDrama) (display)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_performance',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (Annals): Display'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_performance_brit_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (BritDrama) (display)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_performance_brit_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (BritDrama)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_performance_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Performance (Annals): Filter'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_publication',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Date of First Publication'),
        ),
        migrations.AlterField(
            model_name='title',
            name='date_first_publication_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Date of First Publication Display'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_annals_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Display Genre (Annals)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_annals_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Filter Genre (Annals)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_brit_display',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Display Genre (BritDrama)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_brit_filter',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Filter Genre (BritDrama)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre_wiggins',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Genre (Wiggins)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='greg',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Greg (Brief)(e.g., 197 for Hamlet)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='stationers_register',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationers Register'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=5000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_alternative_keywords',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Work Alternative Keywords'),
        ),
        migrations.AlterField(
            model_name='title',
            name='total_editions',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Total Editions'),
        ),
    ]
