# Generated by Django 4.0.4 on 2023-10-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_company_name_alter_edition_authors_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='variants',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Variants'),
        ),
        migrations.AddField(
            model_name='title',
            name='stationer_entries_in_register',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Entries in Register'),
        ),
    ]
