# Generated by Django 4.0.4 on 2023-10-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_edition_variants_title_stationer_entries_in_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stationer_entries_in_register',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variants',
        ),
    ]
