# Generated by Django 4.0.4 on 2023-11-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_item_stationer_entries_in_register_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='composition_date',
        ),
    ]
