# Generated by Django 4.0.4 on 2024-04-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_item_composition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_collection_link_fk', to='main.item'),
        ),
    ]
