# Generated by Django 4.0.4 on 2024-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_item_in_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant_links',
            field=models.ManyToManyField(blank=True, to='main.item'),
        ),
    ]
