# Generated by Django 4.0.4 on 2024-04-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_item_variant_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='variant_links',
        ),
    ]
