# Generated by Django 4.0.4 on 2024-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_item_variant_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='variant_links',
            field=models.ManyToManyField(blank=True, to='main.item'),
        ),
    ]
