# Generated by Django 4.0.4 on 2024-04-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_item_variant_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='independent_playbook_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='independent_playbook_link_fk', to='main.item'),
        ),
    ]
