# Generated by Django 4.0.4 on 2024-04-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_item_independent_playbook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='also_in_collection_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='also_in_collection_link_fk', to='main.item'),
        ),
    ]
