# Generated by Django 4.0.4 on 2024-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_item_also_in_collection_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection_contains',
            field=models.ManyToManyField(blank=True, related_name='collection_contains_item', to='main.item'),
        ),
    ]
