# Generated by Django 4.0.4 on 2024-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_item_collection_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection_contains',
            field=models.ManyToManyField(blank=True, related_name='collection_contains_item', to='main.item'),
        ),
    ]
