# Generated by Django 4.0.4 on 2024-04-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_item_collection_contains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collection_contains',
        ),
    ]
