# Generated by Django 4.0.4 on 2024-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_item_collection_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection_contains',
            field=models.ManyToManyField(blank=True, related_name='collection_contains_fk', to='main.item'),
        ),
    ]
