# Generated by Django 4.0.4 on 2024-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_item_collection_contains'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterField(
            model_name='edition',
            name='variants',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Variants'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stationer_additional_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Additional Notes'),
        ),
    ]
