# Generated by Django 4.0.4 on 2024-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_delete_link_alter_edition_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='stationer_entries_in_register',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Stationer: Entries in Register'),
        ),
    ]
